- hosts: devstack_instances
  tasks:

  - name: install pkgs
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - git
      - vim

  - name: Unload kvm_intel module
    shell: modprobe -r kvm_intel
    sudo: yes

  - name: Load kvm_intel module with nested virt option
    shell: modprobe kvm_intel nested=1
    sudo: yes

  - name: clone devstack
    sudo: no
    git: repo=https://github.com/openstack-dev/devstack dest=~/devstack

  - name: send over local.conf
    sudo: no
    template: src=../../templates/localconf.base dest=/home/ubuntu/devstack/local.conf

  - name: modify cinder_branch
    lineinfile: dest=/home/ubuntu/devstack/local.conf regexp=^CINDER_BRANCH= line=CINDER_BRANCH={{ patchset_ref }}
    register: git_sha

  - name: run stack.sh
    sudo: no
    shell: cd /home/ubuntu/devstack; ./stack.sh 2>&1 > /tmp/stack.sh.log.out
    register: stack_result
    async: 2700
    poll: 30
    ignore_errors: true

  - name: Fetch stack.sh.log.out
    sudo: yes
    fetch: src=/tmp/stack.sh.log.out dest={{ results_dir }}/stack.sh.log.out flat=yes validate_md5=no

  - name: Fail the stack.sh task
    fail: msg="Failed to complete stack.sh"
    when: stack_result|failed
